export const motelHomeSummary = 
"MOTEL HOME MUSIC IS AN INDEPENDENT MUSIC COMPOSITION AND PRODUCTION STUDIO CREATING ORIGINAL MUSIC FOR FILM, TV, AND COMMERCIALS. WE ALSO PROVIDE MUSIC SUPERVISION."

